version: "3.9"

services:
  db:
    image: postgres:16
    container_name: sabina_school_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Aspirine1
      POSTGRES_DB: sabina_school
    ports:
      - "5432:5432"
    volumes:
      - sabina_data:/var/lib/postgresql/data

volumes:
  sabina_data:
