version: "3.8"

services:
  app:
    image: yabramov228/sabina-school:latest
    container_name: sabina_school_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - port=3000
      - db_host=db
      - db_port=5432
      - db_user=${db_user}
      - db_password=${db_password}
      - db_name=${db_name}
      - db_sslmode=disable
      - ELASTICSEARCH_URL=http://${es_host}:${es_port}
    depends_on:
      - db
      - elasticsearch
    networks:
      - school_network

  db:
    image: postgres:16-alpine
    container_name: sabina_school_db
    restart: always
    environment:
      POSTGRES_USER: ${db_user}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school_network
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: sabina_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - school_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: sabina_kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - school_network
    ports:
      - "5601:5601"

volumes:
  postgres_data:
    driver: local

  elasticsearch_data:
    driver: local

networks:
  school_network:
    driver: bridge
